package handlers

import (
	"fmt"
	"net/http"

	"github.com/labstack/echo/v5"
	"github.com/open-relay/control-plane/crypto"
	"github.com/pocketbase/pocketbase/apis"
	"github.com/pocketbase/pocketbase/core"
)

// RegisterTemplateHandler registers GET /templates/relay.toml and /api/collections/relays/records/:id/relay.toml
func RegisterTemplateHandler(router *echo.Echo, app core.App, km *crypto.KeyManager) {
	generateToml := func(url string) string {
		if url == "" {
			url = "{url}"
		}
		return fmt.Sprintf(`# Open-Relay Server Configuration
# Generated by Open-Relay Control Plane
[server]
host = "0.0.0.0"
port = 8080
url = "%s"

[store]
type = "filesystem"
path = "/app/data"

[[auth]]
key_id = "%s"
public_key = "%s"
`, url, km.KeyID, km.PublicKeyBase64)
	}

	router.GET("/templates/relay.toml", func(c echo.Context) error {
		c.Response().Header().Set("Content-Disposition", "attachment; filename=\"relay.toml\"")
		c.Response().Header().Set("Content-Type", "text/plain; charset=utf-8")
		return c.String(http.StatusOK, generateToml("{url}"))
	}, apis.ActivityLogger(app))

	router.GET("/api/collections/relays/records/:id/relay.toml", func(c echo.Context) error {
		relayID := c.PathParam("id")
		dao := app.Dao()
		providerURL := "{url}"

		if relayRec, err := dao.FindRecordById("relays", relayID); err == nil {
			providerID := relayRec.GetString("provider")
			if providerID != "" {
				if provRec, err := dao.FindRecordById("providers", providerID); err == nil {
					if u := provRec.GetString("url"); u != "" {
						providerURL = u
					}
				}
			}
		}

		c.Response().Header().Set("Content-Type", "text/plain; charset=utf-8")
		return c.String(http.StatusOK, generateToml(providerURL))
	}, apis.ActivityLogger(app))
}
